"""
Integration Tests for End-to-End Workflow
==========================================

These tests require actual audio fixture files (generated by
``tests/fixtures/generate.py``).  They verify that the pipeline can
read a file, run separation, and produce valid output stems.

Run with::

    pytest tests/integration/ -v --tb=short
"""

from __future__ import annotations

import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))


def _fixture_path(name: str) -> Path:
    """Return the path to a test fixture file.

    Note: _PROJECT_ROOT is already 'tests/', so fixtures live under
    'fixtures/wav/' relative to it (not 'tests/fixtures/wav/').
    """
    return _PROJECT_ROOT / "fixtures" / "wav" / name


class TestAudioIOIntegration:
    """Real-file integration tests for audio I/O (no Demucs needed)."""

    def test_load_and_save_roundtrip(self, tmp_path):
        """Generate a WAV fixture and verify we can load + resave it."""
        from src.core.audio_io import load_audio, save_audio
        import soundfile as sf

        # Ensure fixture exists; generate it if not
        fp = _fixture_path("simple_tone.wav")
        if not fp.exists():
            from tests.fixtures.generate import generate_all
            generate_all()
        assert fp.exists(), "Fixture simple_tone.wav must exist"

        data, sr = load_audio(fp)
        assert data is not None, "load_audio should return a non-None array"
        assert sr > 0, f"Sample rate should be positive, got {sr}"

        # Save to temp location and verify it's readable
        out_file = tmp_path / "roundtrip.wav"
        save_audio(out_file, data, sr=sr)
        assert out_file.exists(), "save_audio should create the output file"

        reloaded_data, _ = sf.read(str(out_file))
        assert len(reloaded_data) > 0, "Reloaded file should have audio data"


class TestPipelineSmoke:
    """Lightweight pipeline smoke test (no GPU required)."""

    def test_process_audio_file_signature(self):
        """Verify process_audio_file can be called with all keyword args."""
        from src.pipeline.process import process_audio_file
        import inspect

        sig = inspect.signature(process_audio_file)
        params = list(sig.parameters.keys())
        assert "input_file" in params
        assert "output_dir" in params

    def test_missing_input_raises_file_not_found(self):
        """Calling with a non-existent file should raise FileNotFoundError."""
        from src.pipeline.process import process_audio_file

        try:
            process_audio_file(
                input_file="/tmp/does_not_exist_98765.wav",
                output_dir="./test_output_placeholder",
            )
        except FileNotFoundError:
            return  # Expected – test passes
        except ImportError as exc:
            if "demucs" in str(exc).lower() or "torch" in str(exc).lower():
                # Demucs not installed yet; that's acceptable for this smoke test
                return
            raise

        raise AssertionError("Expected FileNotFoundError was not raised")


class TestQualityMetricsIntegration:
    """Test quality metrics with real data."""

    def test_validate_stem_integrity(self):
        from src.utils.quality import validate_stem_integrity

        # Non-existent file should fail
        assert validate_stem_integrity("vocals", "/tmp/nonexistent.wav") is False


class TestBatchProcessingConcept:
    """Verify the concept of batch processing (no actual files needed)."""

    def test_multiple_input_paths(self):
        """Test that we can collect multiple input paths for batch processing."""
        from pathlib import Path as P

        fixture_dir = _PROJECT_ROOT / "fixtures" / "wav"
        wav_files = sorted(fixture_dir.glob("*.wav"))
        # At minimum, simple_tone.wav should exist after generation
        assert len(wav_files) >= 1, "At least one WAV fixture should be present"
